### PR TITLE
(REVIEWER NEEDED URGENTLY)(buggy) paginate dms

### PR DESCRIPTION
**Pull request by oblivikun**
I feel like i messed up some code here but i dont know what part

### CODE REVIEW

**Comment by Heinrich-XIAO** [comment]
Why is the limit based on the abs? why the difference and also why abs? shouldnt the difference always be a certain sign? there should just be a limit on the limit and no limit on skip. skip does not affect the performace and if it does, it actaully makes it faster. limit makes it slower, so cap that.

**Review by Heinrich-XIAO — CHANGES_REQUESTED** [review]
Don't cap skip. just cap limit.

**Review by Heinrich-XIAO — APPROVED** [review]

**Comment by Heinrich-XIAO** [comment]
> I feel like i messed up some code here but i dont know what part

Yes, you messed up everything in git and a few other things in the code itself.

**Comment by Heinrich-XIAO** [comment]
bro

**Comment by oblivikun** [comment]
wait was that good to merege

**Pull request merged**
