### PR TITLE
479 pagination for dms

### PR DESCRIPTION
**Pull request by Heinrich-XIAO**
Also, i reverted your merge becaus eyou f'ed up

### CODE REVIEW

**Comment by Heinrich-XIAO** [comment]
Dont merge this

**Comment by Heinrich-XIAO** [comment]
at least not yet.

**Comment by oblivikun** [comment]
because then if there are enough DMs you will have to make a request like skip=240 limit=250 or whatever

**Comment by oblivikun** [comment]
doesnt it make more sense to limit the diffirence because thats how many DMs ur getting

**Comment by Heinrich-XIAO** [comment]
The styles are dog water.

**Comment by oblivikun** [comment]
I like them

**Comment by Heinrich-XIAO** [comment]
no, also the code is dog water. the script is completely in the html **template**

**Comment by oblivikun** [comment]
ok so put it in a diffirent file

**Comment by Heinrich-XIAO** [comment]
it still renders profane dms

**Comment by Heinrich-XIAO** [comment]
because of order of operations. and before or.

**Comment by Heinrich-XIAO** [comment]
it also doesnt even render the dms from the other person.

**Comment by oblivikun** [comment]
Yea that was for testing

**Comment by oblivikun** [comment]
I havent looked at the code but it runs so im going to assume it works

**Pull request merged**
